# This tells Gitlab to run our linting services first
# These are the repos from which we would like to pull our hooks.
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --config, './pyproject.toml', --fix, --ignore, E402 ]
    # Run the formatter.
    - id: ruff-format
      args: [ --config, './pyproject.toml' ]
